# Generated by Django 5.2.3 on 2025-07-05 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_mod"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "assigned_interns",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"user_type": "intern"},
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        limit_choices_to={"user_type__in": ["admin", "manager"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "manager"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects_managed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Enter a short, descriptive title for the task",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional: add task details or steps"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        help_text="Current status of the task",
                        max_length=15,
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True,
                        help_text="Optional: set a deadline for the task",
                        null=True,
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        limit_choices_to={"user_type__in": ["admin", "manager"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "intern"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="accounts.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Daily_Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_summary",
                    models.TextField(help_text="What work did you do today?"),
                ),
                (
                    "time_spent",
                    models.DurationField(help_text="Time spent on the task"),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "remarks",
                    models.TextField(
                        blank=True, help_text="Any remarks or blockers you faced"
                    ),
                ),
                (
                    "intern",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "intern"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_reports",
                        to="accounts.task",
                    ),
                ),
            ],
        ),
    ]
