# Generated by Django 5.2.3 on 2025-07-05 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_project_task_daily_report"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admin",
            name="admin_code",
        ),
    ]
