# Generated by Django 5.2.3 on 2025-07-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_admin_admin_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateField(null=True),
        ),
    ]
