# Generated by Django 5.2.3 on 2025-07-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_project_end_date_alter_project_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(
                help_text="Enter a short, descriptive title for the task",
                max_length=255,
                unique=True,
            ),
        ),
    ]
