# Generated by Django 5.2.3 on 2025-07-08 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_remove_intern_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="assigned_to",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "intern"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_intern",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
