# Generated by Django 5.2.3 on 2025-07-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_task_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_manager",
            field=models.BooleanField(default=False),
        ),
    ]
